### ISSUE TITLE
Kodi Compatibility (esp. Android)

### ISSUE THREAD

**Issue by apoapostolov** [Anthirian/script.filecleaner#36]
I cannot find this script on Kodi RC2 official addon-repo. Is there a reason why it is not listed?

I downloaded it from github as zip and tried to install via Zip but the error message was "Dependencies Not Met. Contact Author"

Can you please get this script to work with Kodi? Thanks!

**Comment by shali3** [comment]
Can I help here? what's need to be done to support Kodi Helix?

**Comment by Anthirian** [comment]
I'm not entirely sure myself. I would need to look into the changes to Kodi for developers and determine if anything breaks functionality. I'm expecting to have some time to look into this next week after my final exams are over. I'll let you know.

**Comment by shali3** [comment]
Cool. Thanks. 
Let me know if I can help in any way.

**Comment by Anthirian** [comment]
I need some help figuring out why Helix is complaining about dependencies, but unfortunately I don't own any Android devices. A debug log of this issue would be very helpful. I have also heard the Raspberry Pi gives the same error. If you own any of these devices, please test the current version from `master` and provide me with some logs. Thanks!

**Comment by shali3** [comment]
I can get a hold of this: http://www.dx.com/p/217396 
Just set the log level in kodi for debug, run it and send you the logs?

**Comment by Anthirian** [comment]
Unless you have to buy it first, I'd like that indeed. Make sure to enable debugging via `advancedsettings.xml` as well as via KFC's settings.

**Comment by shali3** [comment]
No worries. I don't have to buy it.

**Comment by shali3** [comment]
is this the message you are getting? https://www.dropbox.com/s/hx7j4lgzy20xtyb/Screenshot%202015-02-10%2012.49.40.png?dl=0
I cloned the project, zipped the root folder to "script.filecleaner.zip" and installed from zip on my mac and this is what I got.
Did I zip the addon correctly?

**Comment by Anthirian** [comment]
I must have missed your last reply. I think that's what's @apoapostolov was encountering. Could you please upload the entire log for when that happened? I'm very curious what dependencies aren't met.

**Comment by shali3** [comment]
11:22:23 T:140735171482368   DEBUG: GetZipList - Processing zip://%2fUsers%2fshali%2fSource%2fscript.filecleaner.zip/
11:22:23 T:140735171482368   DEBUG: Addon script.filecleaner requires xbmc.gui version 5.0.1 which is not available

This is what I get in the logs

**Comment by shali3** [comment]
When I changed the xbmc.gui version to 5.3.0 in the addon XML it loads the add-on.
See: http://kodi.wiki/view/Addon.xml

**Comment by Anthirian** [comment]
Aha I see. That dependency is only required for the log viewer. I totally forgot I needed to account for the changes in the skinning engine too. Most changes appear to have broken backwards compatibility, which is why earlier versions of dependencies don't appear to work. I'll update the version requirement and push a new version soon. Thanks for the help so far!

**Comment by shali3** [comment]
you're welcome. do you still want me to run this on Android? Maybe after your fix...

**Comment by shali3** [comment]
in the meanwhile I've seen they returned the 3.2.0 version to kodi's repo... I would really love to get the log viewer on my machine.

**Comment by Anthirian** [comment]
It appears to be an easy fix indeed, one I had already committed locally. I'll push the commit soon, but I found another small bug first that I need to fix.

**Comment by Anthirian** [comment]
I pushed the commit, could you check if you can use the log viewer again after installing from zip?

**Comment by shali3** [comment]
Updated the code, zipped, installed, opened the log viewer. All working well. you can see for yourself: https://www.dropbox.com/s/td3sng02pri542j/kodi-filecleaner-install.mov?dl=0

**Comment by Anthirian** [comment]
Glad it's working. I'm gonna keep the issue open for another while until I'm fairly certain other people don't have issues anymore either. Thanks a lot for all the debugging.

**Comment by shali3** [comment]
I'm happy to help.  Do you want me to test it on android as well?

**Comment by Anthirian** [comment]
That would be useful indeed, thanks

**Comment by shali3** [comment]
Just checked on Android with Kodi 14.1.
All working well (including the log viewer)

**Comment by Anthirian** [comment]
Nice, glad to hear it. I'm waiting for a few more people in the forums to post their experiences with it. If all is well I'll update the Kodi repo soon. Thanks for all the help.

**Comment by seburgi** [comment]
I'm on Windows and this fix works for me too. Thanks!

**Comment by shali3** [comment]
Are you releasing a new version to the kodi repo?

**Comment by Anthirian** [comment]
It will be pushed soon yes, but I first want to adress a bug regarding file transfers. Once that is done it will be pushed.

**Comment by Anthirian** [comment]
Closing this issue since the new release is added to the official repository.
