### ISSUE TITLE
Need some help with adding a few lines to your script.

### ISSUE THREAD

**Issue by michaelcrossland** [Anthirian/script.filecleaner#41]
I love you script because it saves so much HD space for TV shows I want to watch but not keep around.
Here is the thing. I use SMB to get all of my stuff from my FreeNAS server I have setup. But because sometimes for whatever reason my computers stop seeing the NetBIOS name for my NAS. But if I smb into it with the IP address I can get into it no mater what. So my SMBs in the DB look like this smb://192.168.0.65/tv/Video/**** you get the point. Now I hope you can understand why I'm asking for the help I am?
So what I was needing to know is in my user settings folder for your addon. What is a template line of code so I can tell the cleaner to not remove anything from xyz folder that can be added to the setting.xml file?

As for the 2nd part I was wanting to see what I would need to mod in the main addon folder so that I could have say upto 9 Exclusions. And be able to have it work on all 9 items.
I found in the main addons settings.xml file where I can add more lines to the Exclusions, but when I do all it does is show up there it does not use them outside of the main 3 items.
Any help with that mod would be great because I know XML coding but as far as PY coding no clue there never had then need to learn it till now. Got a book on it's way but it will be a bit before I can really say I understand how to read the code let alone make it work.

Thanks for the great work keep it up. If I had the money to get you drunk I would 50 times over.
Michael

**Comment by Anthirian** [comment]
I'm sorry, it took me a while to find the time to write you a proper response. I hope I understood your questions correctly. If not, feel free to correct me.

1. I think it would be more useful if you add exclusions the same way you add the videos to the library, as is being suggested in the exclusions tab. This means you have to use the same protocol (SMB) and in your case enter your IP address like you do for scraping.

2. To add one extra exclusion first you have to add the option to the settings menu. For this you edit `settings.xml` and look for lines like the one below.

```xml
<setting label="32404" id="exclusion3" type="folder" default="" subsetting="true" visible="eq(-4,true)" />
```
You add new lines below the last exclusion, increasing the number in `id` and in `visible` by one, e.g.
```xml
<setting label="32404" id="exclusion4" type="folder" default="" subsetting="true" visible="eq(-5,true)" />
```
After you did this you can set it to the correct path using the addon's settings from within Kodi. Keep in mind it doesn't do anything yet at this point. For it to be used, you have to modify two more files. First go to `default.py` and find the line below (it should be around line 312).
```python
exclusions = map(get_setting, [exclusion1, exclusion2, exclusion3])
```
You add the `id` you created in `settings.xml` to this line, making sure it's inside the square brackets. After this you go to `settings.py` and find the lines below (around 45).
```python
exclusion1 = "exclusion1"
exclusion2 = "exclusion2"
exclusion3 = "exclusion3"
```
Add your new exclusion below these lines, again using the `id` chosen above, and finally add the same `id` to the line below (line 56), also between the square brackets.
```python
paths = [disk_space_check_path, holding_folder, create_subdirs, exclusion1, exclusion2, exclusion3]
```
If you followed everything correctly you should now have one more working exclusion set up. Repeat the process if you would like even more exclusions.
